### ISSUE TITLE
Yeni sürüm yayınlanmalı

### ISSUE THREAD

**Issue by ghost** [flarum-lang/turkish#1]
30 günün ardından birçok uzantı geliştirildi ve çevirileri yapıldı. Çeviri paketinin sürümünün yükseltilmesi gerektiğini düşünüyorum.

**Comment by tolgaaaltas** [comment]
En kısa sürede göz atacağım.

<img width="405" alt="image" src="https://user-images.githubusercontent.com/10291048/167376066-0b2c66ec-a1d0-4f91-b231-f1348eb9b9a1.png">
