### ISSUE TITLE
Flarum sticky problem

### ISSUE THREAD

**Issue by umutcandev** [flarum-lang/turkish#16]
The sentence below needs to be corrected.

https://github.com/flarum-lang/turkish/blob/6efdc8b55648232e60f86a2fabf0afe3bc06ff25/locale/flarum-sticky.yml#L17

**Comment by tolgaaaltas** [comment]
> The sentence below needs to be corrected.
> 
> https://github.com/flarum-lang/turkish/blob/6efdc8b55648232e60f86a2fabf0afe3bc06ff25/locale/flarum-sticky.yml#L17

Working on it. Thanks for your report.

**Comment by tolgaaaltas** [comment]
Will be fixed on v.1.15.0.

**Comment by umutcandev** [comment]
The best 💪
