### ISSUE TITLE
ianm/follow-users için güncelleme gerekli.

### ISSUE THREAD

**Issue by muhammetdemirel** [flarum-lang/turkish#19]
ianm/follow-users versiyon 1.3.0 için Flarum 1.7.1 sürümünde güncelleme gerekli.

**Comment by umutcandev** [comment]
Selamlar,
![IMG_20230324_212134](https://user-images.githubusercontent.com/96707573/227608635-af61a245-b521-4c43-89dd-3536935822f4.jpg)

Follow User uzantısının tüm çevirileri halihazırda yapıldı fakat uzantı bakımcısı askeri görevini yerine getirdiği için uzunca bir süre paket üzerinde yeni güncelleme yayınlanamayacak.

Çevirileri yapmaya devam ediyorum, yapılması gereken tek şey branchları yayınlamak fakat bunuda haliyle yapamıyoruz. Anlayışınız için teşekkürler.

**Comment by umutcandev** [comment]
Selamlar,
Güncelleme yayınlandı. İyi forumlar dilerim.
