### ISSUE TITLE
Tags eklentisinde çeviri sorunu

### ISSUE THREAD

**Issue by umutcandev** [flarum-lang/turkish#20]
![IMG_20230417_145033](https://user-images.githubusercontent.com/96707573/232476488-1786d852-40b7-4073-af92-fab4a4300d3b.jpg)

Ekte görülen metin hoş görünmüyor. Aşağıdaki bağlantıda bulunan metnin şu şekilde çevrilmesi daha doğru olabilir. İncelemenizi istiyorum (FYI: @tolgaaaltas ):

```
{count, plural, one {{tags} etiketi} other {{tags} etiketleri}}
```

https://github.com/flarum-lang/turkish/blob/4fb768659cf3dba89ce9d2fa7519369403b9f936/locale/flarum-tags.yml#L71

**Comment by selmanozturk** [comment]
@umutcandev Geri bildirim için teşekkürler. İlgili düzenleme daha önce dahil edilmiş. Ek olarak, [şu düzenleme](https://github.com/flarum-lang/turkish/commit/9635a4430c855de1937877cfc3c32f231f319d7a) ile sözdizimi daha anlanlı hale gelecektir. Tamamlandı olarak işaretliyorum.
