### ISSUE TITLE
Word mistake (turnike must be Turnstile)

### ISSUE THREAD

**Issue by umutcandev** [flarum-lang/turkish#32]
https://github.com/flarum-lang/turkish/blob/d4ce7233663e3a4d257c5af27915e04f9602e986/locale/blomstra-turnstile.yml#L9C59-L9C59

```
help_text: 'Cloudflare hesabınızda <a>buradan</a> Turnike anahtarları oluşturun.'
```

Hello,
This translation error caused by me should be edited as Turnstile.

**Comment by tolgaaaltas** [comment]
Hi @umutcandev,
Thank you for reporting. This one will be fixed in the next update. Happy new year.
