### ISSUE TITLE
Hatalı tarih formatı

### ISSUE THREAD

**Issue by codeXik** [flarum-lang/turkish#45]
Güncel kodda hatalı yazım: scrubber: 'AAAA YYYY'
Doğru kullanım: scrubber: 'MMMM YYYY'
Doğru kullanım: humanTimeShort: 'D MMM' (profil sayfasında)

[FlarumTR Hüseyin Filiz adlı üyenin düzeltmesine istinaden](https://flarumtr.com/u/HuseyinFiliz) açılmıştır.

**Comment by tolgaaaltas** [comment]
Bir sonraki güncelleme ile birlikte çözülecektir.
